const types = {
  TOGGLE_FULL_SCREEN: 'TOGGLE_FULL_SCREEN',
  TOGGLE_PLAYING: 'TOGGLE_PLAYING',
  SET_NOW_PLAYING: 'SET_NOW_PLAYING',
  SET_CURRENT_TIME: 'SET_CURRENT_TIME',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_USER: 'FETCH_USER',
}

export default types